### Testar CPF Inválido (Login Admin CORRETO)
POST http://localhost:8080/clientes
# Esta é a linha de login correta para "admin:123qwe!@#"
Authorization: Basic YWRtaW46MTIzcXdlIUAj
Content-Type: application/json

{
    "nome": "Teste CPF Inválido",
    "cpf": "11111111111",  
    "email": "cpf@invalido.com",
    "endereco": {
        "cep": "01001000"
    },
    "telefones": [
        {
            "tipo": "CELULAR",
            "numero": "11999998888"
        }
    ]
}